name: templaterpone
description: "A Starter Flutter template with pre built Splash Screen with BLoC, Shared Prefs and dio by Ritik Patle."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Data and API
  dio: ^5.7.0
  shared_preferences: ^2.3.2

  # Assets and Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/